resources:
  repositories:
  - repository: tox
    type: github
    endpoint: github
    name: tox-dev/azure-pipelines-template
    ref: refs/tags/0.2

  - repository: extra_qt
    type: github
    endpoint: github
    name: chstan/extra-qt
    ref: master

trigger:
- master
- release

jobs:
- template: run-tox-env.yml@tox
  parameters:
    name: CI
    tox_version: 'tox'
    jobs:
      py37:
        before:
          - template: get-poetry.yml@extra_qt
        image: [linux, windows, macOs]


- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/release') }}:
  - template: publish-pypi.yml@tox
    parameters:
      dependsOn: [CI]
      external_feed: 'extra_qt'
      pypi_remote: ''