resources:
  repositories:
  - repository: tox
    type: github
    endpoint: github
    name: tox-dev/azure-pipelines-template
    ref: refs/tags/0.2

trigger:
- master
- release

# used to use a template here in order to install poetry but
# Azure lazy evaluates template refs and won't allow you to for instance
# template: a.yml@repoA
#   setup_steps:
#     - template: b.yml@repoB
#
# which is pretty crazy IMO.

jobs:
- template: run-tox-env.yml@tox
  parameters:
    name: CI
    tox_version: 'tox'
    jobs:
      py37:
        before:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.7'
          - script: python -m pip install --upgrade pip
          - script: python -m pip install --user poetry
        image: [linux, windows, macOs]


- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/release') }}:
  - template: publish-pypi.yml@tox
    parameters:
      dependsOn: [CI]
      external_feed: 'extra_qt'
      pypi_remote: ''